#!/usr/bin/env python3
"""Generate a crisp built-in 1-bit font table for 4.2" dense UI text."""

import gzip
from pathlib import Path
import importlib.util

UNIFONT_FILE = Path(__file__).with_name("unifont.hex.gz")
OUT_FILE = Path(__file__).resolve().parents[1] / "main" / "calendar_font_data.h"

CRISP_UI_CHARS = (
    "年月日星期第周"
    "一二三四五六七八九十初廿正冬腊"
    "甲乙丙丁戊己庚辛壬癸子丑寅卯辰巳午未申酉戌亥"
    "鼠牛虎兔龙蛇马羊猴鸡狗猪"
    "小寒大寒立春雨水惊蛰春分清明谷雨立夏小满芒种夏至"
    "小暑大暑立秋处暑白露秋分寒露霜降立冬小雪大雪冬至"
    "元旦劳动节国庆妇女儿童元宵端午夕中重阳除"
    "天气晴阴云风级东南西北东北东南西北微和轻强阵"
    "雨雪雾霾沙尘浮扬雷冰雹冻湿热冷转多少无"
    "喵哎网络信息离线使用步骤连接左侧打开配置家庭返回"
    "键模式上下网页上传待办倒计时课程表额度欢迎未设置添加节次教室"
    "暂无今天没有进行中启用等待时间同步联网后显示"
    "未完成项目无事项重点留言板留言居中左对齐日历时钟天气时间"
    "用量看板自动分钟刷新显示时更新余额已用总计请求令牌不可用"
)


def load_gen_font_module():
    path = Path(__file__).with_name("gen_font.py")
    spec = importlib.util.spec_from_file_location("gen_font_source", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def load_unifont(cps):
    needed = set(cps)
    glyphs = {}
    if not UNIFONT_FILE.exists():
        raise FileNotFoundError(f"missing {UNIFONT_FILE}")

    with gzip.open(UNIFONT_FILE, "rt", encoding="ascii") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_s, hex_s = line.split(":", 1)
            cp = int(cp_s, 16)
            if cp not in needed:
                continue
            raw = bytes.fromhex(hex_s)
            glyphs[cp] = list(raw)
            if len(glyphs) == len(needed):
                break
    return glyphs


def ascii_glyph(raw):
    if len(raw) == 16:
        return raw
    if len(raw) == 32:
        return raw[::2]
    raise ValueError(f"bad ASCII glyph size: {len(raw)}")


def cjk_glyph(raw):
    if len(raw) == 32:
        return raw
    if len(raw) == 16:
        out = []
        for b in raw:
            out.extend((b, 0))
        return out
    raise ValueError(f"bad CJK glyph size: {len(raw)}")


def main():
    ascii_cps = list(range(32, 127))
    cjk_basic_cps = range(0x4E00, 0xA000)
    cjk_cps = sorted(set(cjk_basic_cps) | {ord(ch) for ch in CRISP_UI_CHARS})
    glyphs = load_unifont(ascii_cps + cjk_cps)

    missing = [cp for cp in ascii_cps + cjk_cps if cp not in glyphs]
    if missing:
        raise RuntimeError("missing glyphs: " + ", ".join(f"U+{cp:04X}" for cp in missing))

    with OUT_FILE.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/* Auto-generated by tools/gen_calendar_font.py. Do not edit. */\n")
        f.write("/* Source: GNU Unifont 16.0.02, used for 4.2 inch dense UI text. */\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")

        f.write("static const uint8_t cal_font_ascii[95][16] = {\n")
        for cp in ascii_cps:
            data = ", ".join(f"0x{b:02X}" for b in ascii_glyph(glyphs[cp]))
            f.write(f"    {{ {data} }}, /* 0x{cp:02X} */\n")
        f.write("};\n\n")

        f.write("typedef struct { uint32_t cp; uint8_t bmp[32]; } cal_font16_glyph_t;\n\n")
        f.write(f"static const cal_font16_glyph_t cal_font_zh[{len(cjk_cps)}] = {{\n")
        for cp in cjk_cps:
            data = ", ".join(f"0x{b:02X}" for b in cjk_glyph(glyphs[cp]))
            f.write(f"    {{ 0x{cp:04X}, {{ {data} }} }},\n")
        f.write("};\n\n")
        f.write(f"#define CAL_FONT_ZH_COUNT {len(cjk_cps)}\n")

    print(f"Generated {OUT_FILE}")
    print(f"  ASCII: {len(ascii_cps)} glyphs")
    print(f"  CJK:   {len(cjk_cps)} glyphs")


if __name__ == "__main__":
    main()
